/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 14 18:10:51 GMT 2020
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.ComparadorAutonomia;
import main.java.Veiculo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComparadorAutonomia_ESTest extends ComparadorAutonomia_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(1, 3862).when(veiculo0).getAutonomia();
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(3862).when(veiculo0).getAutonomia();
      Veiculo veiculo1 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(1791).when(veiculo1).getAutonomia();
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      // Undeclared exception!
      try { 
        comparadorAutonomia0.compare((Veiculo) null, (Veiculo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.ComparadorAutonomia", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComparadorAutonomia comparadorAutonomia0 = new ComparadorAutonomia();
      Veiculo veiculo0 = mock(Veiculo.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0).when(veiculo0).getAutonomia();
      int int0 = comparadorAutonomia0.compare(veiculo0, veiculo0);
      assertEquals((-1), int0);
  }
}
